$accent = rgb(FF3399)
$bg = rgb(12091A)
$active_border = rgba(FF3399ff) rgba(00F0FFff) 45deg
$inactive_border = rgba(3B1F52ff)

general {
    col.active_border = $active_border
    col.inactive_border = $inactive_border
}
